os:
  - linux
dist: xenial
language: php

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

jobs:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4


before_install:
  - composer install

script:
  - composer test-phpunit-phar

after_success:
  - travis_retry composer ci-coveralls
